#!/bin/sh

set -eu

herdr_bin=${HERDR_BIN_PATH:-herdr}

"$herdr_bin" plugin pane open \
	--plugin local.workspace-kinds \
	--entrypoint create \
	--placement popup \
	--width '70%' \
	--height 18 \
	--focus >/dev/null
