matches:
  - regex: ";;ES (?P<name>.*);"
    replace: |-
      import { Effect } from 'effect';

      export class {{name}}
      	extends Effect.Service<{{name}}>()('{{name}}',
      		{
      		dependencies: [],
      		effect: Effect.gen(function*()
      			{
              const x$|$ = (arg1: unknown): Effect.Effect<void> => Effect.gen(function*() {  })

      				return {

      				};
      			}),
      		accessors: true
      	})
      {}
